//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMClinicAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderHeader
    {
        
        public PurchaseOrderHeader()
        {
            this.PurchaseOrderDrugLines = new HashSet<PurchaseOrderDrugLine>();
        }
    
        public int POID { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string Note { get; set; }
    
        
        public virtual ICollection<PurchaseOrderDrugLine> PurchaseOrderDrugLines { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
