//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMClinicAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PurchaseOrderHeader
    {
        
        public PurchaseOrderHeader()
        {
            this.PurchaseOrderDrugLines = new HashSet<PurchaseOrderDrugLine>();
        }
    
        public int POID { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Purchase Order Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Range(typeof(DateTime), minimum: "1/2/1990", maximum: "31/12/2029",
    ErrorMessage = "Value for {0} must be between {1} and {2}")]
        public Nullable<System.DateTime> PODate { get; set; } = DateTime.Today;
        public Nullable<int> SupplierID { get; set; }
        public string Note { get; set; }
    
        
        public virtual ICollection<PurchaseOrderDrugLine> PurchaseOrderDrugLines { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
