//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMClinicAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDrugLine
    {
        public int PODrugProdLineID { get; set; }
        public int POID { get; set; }
        public int DrugID { get; set; }
        public int Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
    
        public virtual drug drug { get; set; }
        public virtual PurchaseOrderHeader PurchaseOrderHeader { get; set; }
    }
}
